/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContainersRouteImport } from './routes/containers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ContainersIndexRouteImport } from './routes/containers.index'
import { Route as ProjectsNameRouteImport } from './routes/projects.$name'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as ContainersIdRouteImport } from './routes/containers.$id'

const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersRoute = ContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ContainersIndexRoute = ContainersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContainersRoute,
} as any)
const ProjectsNameRoute = ProjectsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ProjectsRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersIdRoute = ContainersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContainersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/containers': typeof ContainersRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/registry': typeof RegistryRoute
  '/containers/$id': typeof ContainersIdRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/projects/$name': typeof ProjectsNameRoute
  '/containers/': typeof ContainersIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/registry': typeof RegistryRoute
  '/containers/$id': typeof ContainersIdRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/projects/$name': typeof ProjectsNameRoute
  '/containers': typeof ContainersIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/containers': typeof ContainersRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/registry': typeof RegistryRoute
  '/containers/$id': typeof ContainersIdRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/projects/$name': typeof ProjectsNameRoute
  '/containers/': typeof ContainersIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/containers'
    | '/login'
    | '/projects'
    | '/registry'
    | '/containers/$id'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/projects/$name'
    | '/containers/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/registry'
    | '/containers/$id'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/projects/$name'
    | '/containers'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/containers'
    | '/login'
    | '/projects'
    | '/registry'
    | '/containers/$id'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/projects/$name'
    | '/containers/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContainersRoute: typeof ContainersRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RegistryRoute: typeof RegistryRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers': {
      id: '/containers'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof ContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/containers/': {
      id: '/containers/'
      path: '/'
      fullPath: '/containers/'
      preLoaderRoute: typeof ContainersIndexRouteImport
      parentRoute: typeof ContainersRoute
    }
    '/projects/$name': {
      id: '/projects/$name'
      path: '/$name'
      fullPath: '/projects/$name'
      preLoaderRoute: typeof ProjectsNameRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/$id': {
      id: '/containers/$id'
      path: '/$id'
      fullPath: '/containers/$id'
      preLoaderRoute: typeof ContainersIdRouteImport
      parentRoute: typeof ContainersRoute
    }
  }
}

interface ContainersRouteChildren {
  ContainersIdRoute: typeof ContainersIdRoute
  ContainersIndexRoute: typeof ContainersIndexRoute
}

const ContainersRouteChildren: ContainersRouteChildren = {
  ContainersIdRoute: ContainersIdRoute,
  ContainersIndexRoute: ContainersIndexRoute,
}

const ContainersRouteWithChildren = ContainersRoute._addFileChildren(
  ContainersRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsNameRoute: typeof ProjectsNameRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsNameRoute: ProjectsNameRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContainersRoute: ContainersRouteWithChildren,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RegistryRoute: RegistryRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
